/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.21 from the
 * contents of MouseX-MethodAttributes.xs. Do not edit this file, edit MouseX-MethodAttributes.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "MouseX-MethodAttributes.xs"
#define PERL_NO_GET_CONTEXT
#include <EXTERN.h>
#include <perl.h>
#include <XSUB.h>

#define NEED_newSVpvn_flags
#include "ppport.h"

#ifndef newSVpvs_share
#define newSVpvs_share(s) Perl_newSVpvn_share(aTHX_ s, sizeof(s)-1, 0U)
#endif

static SV*
mx_ma_get_name(pTHX) {
    STRLEN len;
    const char* name = SvPV_const(PL_subname, len);

    I32 pos = len;

    while(pos > 0){
        if(name[--pos] == ':'){
            I32 const distance = len - pos - 1;
            return newSVpvn_flags(name + len - distance, distance, SVs_TEMP);
        }
    }
    return newSVpvn_flags(name, pos, SVs_TEMP);
}

static SV*
mx_ma_get_meta(pTHX_ SV* const klass) {
    dSP;
    SV* meta;

    PUSHMARK(SP);
    EXTEND(SP, 3);
    mPUSHs(newSVpvs_share("MouseX::MethodAttributes"));
    mPUSHs(newSVpvs_share("for_class"));
    PUSHs(klass);
    PUTBACK;
    call_method("init_meta", G_VOID | G_DISCARD);

    SPAGAIN;

    PUSHMARK(SP);
    XPUSHs(klass);
    PUTBACK;
    call_method("meta", G_SCALAR);
    SPAGAIN;
    meta = POPs;
    PUTBACK;

    return meta;
}

#line 65 "MouseX-MethodAttributes.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 117 "MouseX-MethodAttributes.c"

XS(XS_MouseX__MethodAttributes__Role__AttrContainer_MODIFY_CODE_ATTRIBUTES); /* prototype to pass -Wmissing-prototypes */
XS(XS_MouseX__MethodAttributes__Role__AttrContainer_MODIFY_CODE_ATTRIBUTES)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2)
       croak_xs_usage(cv,  "klass, code, ...");
    {
	SV*	klass = ST(0);
#line 62 "MouseX-MethodAttributes.xs"
{
    SV* const name = mx_ma_get_name(aTHX);
    SV* const meta = mx_ma_get_meta(aTHX_ klass);
    I32 i;

    PUSHMARK(SP);
    EXTEND(SP, items);
    PUSHs(meta);
    PUSHs(name);
    for(i = 2; i < items; i++){
        PUSHs(ST(i));
    }
    PUTBACK;
    call_method("register_method_attributes", G_VOID | G_DISCARD);
}
#line 147 "MouseX-MethodAttributes.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_MouseX__MethodAttributes); /* prototype to pass -Wmissing-prototypes */
XS(boot_MouseX__MethodAttributes)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        (void)newXS("MouseX::MethodAttributes::Role::AttrContainer::MODIFY_CODE_ATTRIBUTES", XS_MouseX__MethodAttributes__Role__AttrContainer_MODIFY_CODE_ATTRIBUTES, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

